AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Portfolio Website Backend API

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.11
    Environment:
      Variables:
        DATA_TABLE: !Ref DataTable
        JWT_SECRET: !Ref JWTSecret
        REDIS_URL: !Ref RedisUrl
        CLOUDINARY_URL: !Ref CloudinaryUrl

Resources:
  # API Gateway
  PortfolioApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: PortfolioApi
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: AWS_IAM

  # Single DynamoDB Table with GSIs
  DataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: DataTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: N
        - AttributeName: GSI2PK
          AttributeType: S
        - AttributeName: GSI2SK
          AttributeType: S
        - AttributeName: GSI3PK
          AttributeType: S
        - AttributeName: GSI3SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        # GSI1: Blogs sorted by date (for listing all blogs)
        - IndexName: BlogsByDate
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        # GSI2: Blog lookup by slug
        - IndexName: BlogBySlug
          KeySchema:
            - AttributeName: GSI2PK
              KeyType: HASH
            - AttributeName: GSI2SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        # GSI3: Likes by blog
        - IndexName: LikesByBlog
          KeySchema:
            - AttributeName: GSI3PK
              KeyType: HASH
            - AttributeName: GSI3SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: TTL

  # Lambda Functions
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PortfolioAuthFunction
      CodeUri: src/
      Handler: handlers.auth.lambda_handler
      Events:
        Login:
          Type: Api
          Properties:
            RestApiId: !Ref PortfolioApi
            Path: /auth/login
            Method: post

  PortfolioFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PortfolioFunction
      CodeUri: src/
      Handler: handlers.portfolio.lambda_handler
      Events:
        GetPortfolio:
          Type: Api
          Properties:
            RestApiId: !Ref PortfolioApi
            Path: /portfolio
            Method: get
        UpdatePortfolio:
          Type: Api
          Properties:
            RestApiId: !Ref PortfolioApi
            Path: /portfolio
            Method: put

  BlogsGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: BlogsGetFunction
      CodeUri: src/
      Handler: handlers.blogs_get.lambda_handler
      Events:
        GetBlogs:
          Type: Api
          Properties:
            RestApiId: !Ref PortfolioApi
            Path: /blogs
            Method: get
        GetBlog:
          Type: Api
          Properties:
            RestApiId: !Ref PortfolioApi
            Path: /blogs/{id}
            Method: get

  BlogsCreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: BlogsCreateFunction
      CodeUri: src/
      Handler: handlers.blogs_create.lambda_handler
      Events:
        CreateBlog:
          Type: Api
          Properties:
            RestApiId: !Ref PortfolioApi
            Path: /blogs
            Method: post

  BlogsUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: BlogsUpdateFunction
      CodeUri: src/
      Handler: handlers.blogs_update.lambda_handler
      Events:
        UpdateBlog:
          Type: Api
          Properties:
            RestApiId: !Ref PortfolioApi
            Path: /blogs/{id}
            Method: put

  BlogsDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: BlogsDeleteFunction
      CodeUri: src/
      Handler: handlers.blogs_delete.lambda_handler
      Events:
        DeleteBlog:
          Type: Api
          Properties:
            RestApiId: !Ref PortfolioApi
            Path: /blogs/{id}
            Method: delete

  LikesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: LikesFunction
      CodeUri: src/
      Handler: handlers.likes.lambda_handler
      Events:
        LikeBlog:
          Type: Api
          Properties:
            RestApiId: !Ref PortfolioApi
            Path: /blogs/{id}/likes
            Method: post
        GetLikes:
          Type: Api
          Properties:
            RestApiId: !Ref PortfolioApi
            Path: /blogs/{id}/likes
            Method: get

  # Parameters
  JWTSecret:
    Type: String
    Description: JWT Secret Key
    NoEcho: true

  RedisUrl:
    Type: String
    Description: Upstash Redis URL
    NoEcho: true

  CloudinaryUrl:
    Type: String
    Description: Cloudinary URL
    NoEcho: true

Outputs:
  PortfolioApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${PortfolioApi}.execute-api.${AWS::Region}.amazonaws.com/prod/'
